### ISSUE TITLE
:hover pseudo-class optimization

### ISSUE THREAD

**Issue by dongyuwei** [jakesgordon/sprite-factory#26]
instead of 

``` css
.icon-top { width: 25px; height: 12px; background: url(arrow.png) -733px -589px no-repeat; }
.icon-top:hover { width: 25px; height: 12px; background: url(arrow.png) -703px -606px no-repeat;}
```

we can do optimization like this(only set **background-position** of :hover pseudo-class):

``` css
.icon-top { width: 25px; height: 12px; background: url(arrow.png) -733px -589px no-repeat; }
.icon-top:hover { background-position: -703px -606px ; }
```

This way, we can reduce a HTTP request(maybe a 304 response), and reduce the size of .css file.

I have a patch(see https://github.com/dongyuwei/sprite-factory/blob/master/lib/sprite_factory/style.rb ):

```
def self.generate(style_name, selector, path, images)
      styles = []
      images.each do |image|
        if image[:filename].index("--hover")
          attr = [
            "background-position: #{-image[:cssx]}px #{-image[:cssy]}px"
          ]
        else
          attr = [
            "width: #{image[:cssw]}px",
            "height: #{image[:cssh]}px",
            "background: url(#{path}) #{-image[:cssx]}px #{-image[:cssy]}px no-repeat"
          ]
        end
        image[:path] = path
        image[:selector] = selector
        image[:style] = send("#{style_name}_style", attr) # make pure style available for (optional) custom rule generators (see usage of yield inside Runner#style)
        styles << send(style_name, selector, image[:name], attr)
      end
      styles << ""
      styles.join("\n")
end
```
